### GET / (endpoint) to see if the page loads
GET http://localhost:<PORT>

### POST /auth/register (endpoint) user sign up
POST http://localhost:<PORT>/auth/register
Content-Type: application/json

{
    "username": "alex1200@gmail.com",
    "password": "123xyz"
}

### POST /auth/login (endpoint) user log in
POST http://localhost:<PORT>/auth/login
Content-Type: application/json

{
    "username": "alex1200@gmail.com",
    "password": "123xyz"
}

### GET /todos (protected endpoint) all of users todos
GET http://localhost:<PORT>/todos
Authorization: <token>

### POST /todos (protected endpoint) new todo
POST http://localhost:<PORT>/todos
Authorization: <token>
Content-type: application/json

{
    "task" : "Get eggs later",
    "completed": 0
}


### PUT /todos/:id (protected endpoint) update a  todo
PUT http://localhost:<PORT>/todos/2
Authorization: <token>
Content-type: application/json 

{
    "completed": 1
}

### DELETE /todos/:id (protected endpoint) delete a todo
DELETE http://localhost:<PORT>/todos/2
Authorization: <token>

